services:
  open-speech:
    extends:
      file: docker-compose.yml
      service: open-speech
    environment:
      - STT_MODEL=${STT_MODEL:-Systran/faster-whisper-base}
      - OS_WYOMING_ENABLED=${OS_WYOMING_ENABLED:-false}
      - OS_WYOMING_HOST=${OS_WYOMING_HOST:-127.0.0.1}
      - OS_MAX_LOADED_MODELS=${OS_MAX_LOADED_MODELS:-0}

volumes:
  hf-cache:
  vad-cache:
  ssl-certs:
  tts-cache:
